name: iso_build
on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
      - main

jobs:
  getvars:
    runs-on: ubuntu-latest
    steps:
      - id: outputs
        run: |
          echo "ubuntu_version=$(curl -skL https://github.com/manjaro/release-review/raw/master/.github/workflows/iso_build.yaml | awk '/runs-on/ {print $NF}' | tail -n 1)" >> $GITHUB_OUTPUT
          echo "kernel_version=$(curl -skL https://github.com/manjaro/release-review/raw/master/.github/workflows/iso_build.yaml | awk '/kernel/ {print $NF}')" >> $GITHUB_OUTPUT
          echo "manjaro_version=$(curl -skL https://github.com/manjaro/release-review/raw/master/.github/workflows/iso_build.yaml | awk '/version/ {print $NF}')" >> $GITHUB_OUTPUT

  build:
    needs: getvars
    runs-on: ${{needs.getvars.outputs.ubuntu_version}}
    strategy:
      matrix:
        EDITION: [gnome]
        BRANCH: [stable]
        SCOPE: [minimal]
    steps:
      - uses: styfle/cancel-workflow-action@main
        with:
          access_token: ${{ github.token }}
      - name: Checkout manjaro-iso-action
        uses: actions/checkout@main
        with:
          repository: manjaro/manjaro-iso-action
          path: manjaro-iso-action
      - name: Checkout myself
        uses: actions/checkout@main
      - name: Custom
        run: |
          sudo bash custom.sh
      - name: image-build
        uses: ./manjaro-iso-action
        with:
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          kernel: ${{needs.getvars.outputs.kernel_version}}
          version: ${{needs.getvars.outputs.manjaro_version}}
      - name: Push to transfer
        env:
          WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
        run: |
          env
          bash main/transfer.sh $(find . -name "manjaro-*.iso")
